DROP TABLE IF EXISTS ungrd_db.ungrd_proyecto_camilosilva;

CREATE EXTERNAL TABLE ungrd_db.ungrd_proyecto_camilosilva (
  `nombre_entidad` string,
  `nit_entidad` string,
  `departamento` string,
  `ciudad` string,
  `localizaci_n` string,
  `orden` string,
  `sector` string,
  `rama` string,
  `entidad_centralizada` string,
  `proceso_de_compra` string,
  `id_contrato` string,
  `referencia_del_contrato` string,
  `estado_contrato` string,
  `codigo_de_categoria_principal` string,
  `descripcion_del_proceso` string,
  `tipo_de_contrato` string,
  `modalidad_de_contratacion` string,
  `justificacion_modalidad_de` string,
  `fecha_de_firma` string,
  `fecha_de_inicio_del_contrato` string,
  `fecha_de_fin_del_contrato` string,
  `condiciones_de_entrega` string,
  `tipodocproveedor` string,
  `documento_proveedor` string,
  `proveedor_adjudicado` string,
  `es_grupo` string,
  `es_pyme` string,
  `habilita_pago_adelantado` string,
  `liquidaci_n` string,
  `obligaci_n_ambiental` string,
  `obligaciones_postconsumo` string,
  `reversion` string,
  `origen_de_los_recursos` string,
  `destino_gasto` string,
  `valor_del_contrato` string,
  `valor_de_pago_adelantado` string,
  `valor_facturado` string,
  `valor_pendiente_de_pago` string,
  `valor_pagado` string,
  `valor_amortizado` string,
  `valor_pendiente_de` string,
  `valor_pendiente_de_ejecucion` string,
  `saldo_cdp` string,
  `saldo_vigencia` string,
  `espostconflicto` string,
  `dias_adicionados` string,
  `puntos_del_acuerdo` string,
  `pilares_del_acuerdo` string,
  `urlproceso` string,
  `nombre_representante_legal` string,
  `nacionalidad_representante_legal` string,
  `domicilio_representante_legal` string,
  `tipo_de_identificaci_n_representante_legal` string,
  `identificaci_n_representante_legal` string,
  `g_nero_representante_legal` string,
  `presupuesto_general_de_la_nacion_pgn` string,
  `sistema_general_de_participaciones` string,
  `sistema_general_de_regal_as` string,
  `recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_` string,
  `recursos_de_credito` string,
  `recursos_propios` string,
  `ultima_actualizacion` string,
  `codigo_entidad` string,
  `codigo_proveedor` string,
  `fecha_inicio_liquidacion` string,
  `fecha_fin_liquidacion` string,
  `objeto_del_contrato` string,
  `duraci_n_del_contrato` string,
  `nombre_del_banco` string,
  `tipo_de_cuenta` string,
  `n_mero_de_cuenta` string,
  `el_contrato_puede_ser_prorrogado` string,
  `fecha_de_notificaci_n_de_prorrogaci_n` string,
  `nombre_ordenador_del_gasto` string,
  `tipo_de_documento_ordenador_del_gasto` string,
  `n_mero_de_documento_ordenador_del_gasto` string,
  `nombre_supervisor` string,
  `tipo_de_documento_supervisor` string,
  `n_mero_de_documento_supervisor` string,
  `nombre_ordenador_de_pago` string,
  `tipo_de_documento_ordenador_de_pago` string,
  `n_mero_de_documento_ordenador_de_pago` string,
  `documentos_tipo` string,
  `descripcion_documentos_tipo` string,
  `direcci_n_de_ejecuci_n_del_contrato` string
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  "separatorChar" = ",",
  "quoteChar" = "\""
)
STORED AS TEXTFILE
LOCATION 's3://ungrd-proyecto-camilosilva/'
TBLPROPERTIES ("skip.header.line.count"="1");
